apiVersion: v1
kind: Service
metadata:
  name: service-nginx
spec:
  type: LoadBalancer
  selector:
    app: deployment-nginx
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
    nodePort: 443
  - name: ssh
    port: 22
    nodePort: 22
  - name: wp
    port: 5050
    nodePort: 5050
  - name: pma
    port: 5000
    nodePort: 5000
