apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-wordpress
spec:
  selector:
    matchLabels:
      app: deployment-wordpress
  template:
    metadata:
      labels:
        app: deployment-wordpress
    spec:
      containers:
      - name: wordpress
        image: my-wordpress
        imagePullPolicy: Never
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: "WORDPRESS_DB_HOST"
          value: "service-mysql.default.svc.cluster.local:3306"
        - name: "WORDPRESS_DB_USER"
          value: "bruhuser"
        - name: "WORDPRESS_DB_PASSWORD"
          value: "bruhpass"
        - name: "WORDPRESS_DB_NAME"
          value: "wordpress"
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: pstore-wordpress
          mountPath: /var/www/html
      volumes:
      - name: pstore-wordpress
        persistentVolumeClaim:
          claimName: pvc-wordpress
